import React, { useEffect, useState, useRef } from 'react';
import { get, post, del, API_BASE_URL, CHURCH_NAME } from '@/lib/api';
import { FileText, Plus, Loader2, X, Eye, Trash2, Printer, Download, Search, RefreshCw, AlertCircle, CheckCircle, Globe } from 'lucide-react';
import { toast } from 'sonner';

// ── Types ─────────────────────────────────────────────────────
interface RecLetter {
  id: string;
  applicant_name: string;
  applicant_status?: string;
  date_joined?: string;
  additional_info?: string;
  org_name?: string;
  org_website?: string;
  org_type?: string;
  org_description?: string;
  purpose?: string;
  extra_info?: string;
  letter_type: 'church' | 'choir';
  letter_content: string;
  signatory_name?: string;
  signatory_title?: string;
  generated_by_first?: string;
  generated_by_last?: string;
  generated_at: string;
  status: string;
}

interface LetterMeta {
  church_name: string;
  logo_url: string;
  church_contact: string;
}

// ── Print / Download helper ───────────────────────────────────
function printLetter(letter: RecLetter, meta: LetterMeta) {
  const w = window.open('', '_blank', 'width=900,height=1100');
  if (!w) { alert('Please allow popups to print.'); return; }

  const logoHtml = meta.logo_url
    ? `<img src="${meta.logo_url}" style="height:70px;width:auto;object-fit:contain;margin-bottom:8px" alt="logo" />`
    : '';
  const entity = letter.letter_type === 'choir' ? `${meta.church_name} Choir` : meta.church_name;

  // Convert plain text letter to HTML paragraphs
  const bodyHtml = letter.letter_content
    .split('\n\n')
    .map((para) => {
      const trimmed = para.trim();
      if (!trimmed) return '';
      // Signature block
      if (trimmed.startsWith('____')) return `<div class="sig-line"></div>`;
      return `<p>${trimmed.replace(/\n/g, '<br/>')}</p>`;
    })
    .join('');

  w.document.write(`<!doctype html><html><head><meta charset="UTF-8">
<title>Recommendation Letter – ${letter.applicant_name}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Times New Roman', Times, serif; font-size: 12pt; color: #1a1a1a; background: #fff; }
  .page { max-width: 750px; margin: 0 auto; padding: 60px 70px; min-height: 100vh; }
  .letterhead { display: flex; align-items: flex-start; justify-content: space-between; border-bottom: 3px solid #5b21b6; padding-bottom: 20px; margin-bottom: 30px; }
  .letterhead-left { display: flex; align-items: center; gap: 16px; }
  .church-name { font-size: 20pt; font-weight: bold; color: #5b21b6; line-height: 1.2; }
  .church-entity { font-size: 11pt; color: #6b7280; margin-top: 2px; }
  .church-contact { font-size: 9pt; color: #6b7280; text-align: right; line-height: 1.8; }
  .letter-body p { margin-bottom: 14px; line-height: 1.8; text-align: justify; }
  .letter-body p:first-child { margin-bottom: 20px; }
  .sig-line { border-bottom: 2px solid #1a1a1a; width: 260px; margin: 40px 0 8px 0; }
  .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 12px; text-align: center; font-size: 9pt; color: #9ca3af; }
  @media print {
    body { font-size: 11pt; }
    .page { padding: 40px 50px; }
    .no-print { display: none; }
  }
</style>
</head><body>
<div class="page">
  <div class="letterhead">
    <div class="letterhead-left">
      ${logoHtml}
      <div>
        <div class="church-name">${meta.church_name}</div>
        <div class="church-entity">${entity}</div>
      </div>
    </div>
    <div class="church-contact">${meta.church_contact.replace(/ \| /g, '<br/>')}</div>
  </div>
  <div class="letter-body">${bodyHtml}</div>
  <div class="footer">
    This letter was generated by ${meta.church_name} Management System on ${new Date(letter.generated_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
  </div>
</div>
<script>window.onload = () => setTimeout(() => window.print(), 600);</script>
</body></html>`);
  w.document.close();
}

// ── Form Component ────────────────────────────────────────────
const LetterForm: React.FC<{ onClose: () => void; onSuccess: (letter: RecLetter, meta: LetterMeta) => void }> = ({ onClose, onSuccess }) => {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [saving, setSaving] = useState(false);
  const [lookingUp, setLookingUp] = useState(false);
  const [orgLookupResult, setOrgLookupResult] = useState<{ success: boolean; error?: string; org?: any } | null>(null);

  const [form, setForm] = useState({
    applicant_name: '', applicant_status: '', date_joined: '', additional_info: '',
    org_name: '', org_website: '', org_type: '', org_description: '', purpose: '', extra_info: '',
    letter_type: 'church' as 'church' | 'choir',
  });

  const upd = (k: string, v: string) => setForm((f) => ({ ...f, [k]: v }));

  const lookupOrg = async () => {
    if (!form.org_website) return;
    setLookingUp(true);
    setOrgLookupResult(null);
    try {
      const res = await post<any>('/rec-letters/lookup-org', { url: form.org_website });
      setOrgLookupResult(res);
      if (res.success && res.org) {
        if (res.org.name && !form.org_name) upd('org_name', res.org.name);
        if (res.org.description && !form.org_description) upd('org_description', res.org.description);
        toast.success('Organization info retrieved');
      } else {
        toast.warning(res.error || 'Could not retrieve org info — please enter manually');
      }
    } catch {
      setOrgLookupResult({ success: false, error: 'Lookup failed' });
      toast.error('Could not reach that URL. Please enter organization info manually.');
    } finally {
      setLookingUp(false);
    }
  };

  const submit = async () => {
    if (!form.applicant_name.trim()) { toast.error('Applicant name is required'); return; }
    setSaving(true);
    try {
      const res = await post<any>('/rec-letters', form);
      toast.success('Recommendation letter generated!');
      onSuccess(res.letter, { church_name: res.church_name, logo_url: res.logo_url, church_contact: res.church_contact });
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[92vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="bg-gradient-to-br from-purple-700 to-indigo-800 px-6 py-4 text-white sticky top-0 z-10">
          <button onClick={onClose} className="absolute right-4 top-4 p-1 rounded-full hover:bg-white/20"><X size={20} /></button>
          <h3 className="text-xl font-bold flex items-center gap-2"><FileText size={22} /> New Recommendation Letter</h3>
          <div className="flex gap-2 mt-3">
            {[1,2,3].map((s) => (
              <div key={s} className={`flex items-center gap-1 text-xs font-semibold px-3 py-1 rounded-full ${step === s ? 'bg-white text-purple-700' : step > s ? 'bg-white/30 text-white' : 'bg-white/10 text-white/60'}`}>
                {step > s ? <CheckCircle size={12} /> : s}
                {s === 1 ? ' Applicant' : s === 2 ? ' Organization' : ' Generate'}
              </div>
            ))}
          </div>
        </div>

        <div className="p-6 space-y-4">
          {/* Step 1: Applicant */}
          {step === 1 && (
            <>
              <h4 className="font-semibold text-gray-800">Applicant Information</h4>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Full Name *</label>
                <input value={form.applicant_name} onChange={(e) => upd('applicant_name', e.target.value)} className="input-base" placeholder="e.g. John Kwame Mensah" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Relationship / Status with Church or Choir</label>
                <input value={form.applicant_status} onChange={(e) => upd('applicant_status', e.target.value)} className="input-base" placeholder="e.g. Active Choir Member, Faithful Church Member" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Date / Month / Year They Joined</label>
                <input value={form.date_joined} onChange={(e) => upd('date_joined', e.target.value)} className="input-base" placeholder="e.g. January 2020, or 3 years ago" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Additional Relevant Information</label>
                <textarea rows={3} value={form.additional_info} onChange={(e) => upd('additional_info', e.target.value)} className="input-base resize-none" placeholder="Any specific achievements, roles, or qualities to highlight..." />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Letter Type *</label>
                <div className="grid grid-cols-2 gap-3">
                  {(['church','choir'] as const).map((t) => (
                    <button key={t} type="button" onClick={() => upd('letter_type', t)}
                      className={`rounded-xl border-2 py-3 text-sm font-semibold capitalize transition-all ${form.letter_type === t ? 'border-purple-600 bg-purple-50 text-purple-700' : 'border-gray-200 text-gray-600 hover:border-gray-300'}`}>
                      {t === 'church' ? '⛪ Church Recommendation' : '🎵 Choir Recommendation'}
                    </button>
                  ))}
                </div>
              </div>
              <div className="flex justify-end pt-2">
                <button onClick={() => { if (!form.applicant_name.trim()) { toast.error('Applicant name required'); return; } setStep(2); }} className="btn-primary">Next: Organization →</button>
              </div>
            </>
          )}

          {/* Step 2: Organization */}
          {step === 2 && (
            <>
              <h4 className="font-semibold text-gray-800">Letter Destination</h4>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Organization Website URL</label>
                <div className="flex gap-2">
                  <input value={form.org_website} onChange={(e) => upd('org_website', e.target.value)} className="input-base flex-1" placeholder="https://www.university.edu" />
                  <button onClick={lookupOrg} disabled={lookingUp || !form.org_website} className="btn-outline px-3 py-2 text-sm whitespace-nowrap">
                    {lookingUp ? <Loader2 size={16} className="animate-spin" /> : <Globe size={16} />}
                    {lookingUp ? 'Looking up…' : 'Lookup'}
                  </button>
                </div>
                {orgLookupResult && (
                  <div className={`mt-2 p-3 rounded-lg text-sm flex items-start gap-2 ${orgLookupResult.success ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-700'}`}>
                    {orgLookupResult.success ? <CheckCircle size={16} className="shrink-0 mt-0.5" /> : <AlertCircle size={16} className="shrink-0 mt-0.5" />}
                    {orgLookupResult.success ? 'Organization info retrieved. Review and edit below.' : `${orgLookupResult.error} — Please enter organization details manually.`}
                  </div>
                )}
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Organization Name *</label>
                <input value={form.org_name} onChange={(e) => upd('org_name', e.target.value)} className="input-base" placeholder="e.g. University of Ghana, Accra Technical University" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Organization Type</label>
                <input value={form.org_type} onChange={(e) => upd('org_type', e.target.value)} className="input-base" placeholder="e.g. University, Company, NGO, Government Agency" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Organization Description (optional)</label>
                <textarea rows={2} value={form.org_description} onChange={(e) => upd('org_description', e.target.value)} className="input-base resize-none" placeholder="Brief description of the organization..." />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Purpose of Recommendation *</label>
                <input value={form.purpose} onChange={(e) => upd('purpose', e.target.value)} className="input-base" placeholder="e.g. admission to the Music Department, employment as a worship coordinator" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Additional Information to Include</label>
                <textarea rows={2} value={form.extra_info} onChange={(e) => upd('extra_info', e.target.value)} className="input-base resize-none" placeholder="Any other specific information the applicant wants included..." />
              </div>
              <div className="flex justify-between pt-2">
                <button onClick={() => setStep(1)} className="btn-outline">← Back</button>
                <button onClick={() => { if (!form.org_name.trim()) { toast.error('Organization name required'); return; } setStep(3); }} className="btn-primary">Next: Generate →</button>
              </div>
            </>
          )}

          {/* Step 3: Review & Generate */}
          {step === 3 && (
            <>
              <h4 className="font-semibold text-gray-800">Review & Generate</h4>
              <div className="bg-gray-50 rounded-xl p-4 space-y-2 text-sm">
                <div className="grid grid-cols-2 gap-2">
                  {[
                    ['Applicant', form.applicant_name],
                    ['Status', form.applicant_status || '—'],
                    ['Joined', form.date_joined || '—'],
                    ['Letter Type', form.letter_type === 'church' ? '⛪ Church' : '🎵 Choir'],
                    ['Organization', form.org_name || '—'],
                    ['Purpose', form.purpose || '—'],
                  ].map(([k, v]) => (
                    <div key={k}>
                      <span className="text-gray-500 text-xs uppercase font-semibold">{k}</span>
                      <div className="font-medium text-gray-800">{v}</div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 text-sm text-blue-700">
                <strong>Note:</strong> The signatory (Pastor or Choir Director) will be automatically fetched from your Leadership CMS. The letter will be generated with all the information above.
              </div>
              <div className="flex justify-between pt-2">
                <button onClick={() => setStep(2)} className="btn-outline">← Back</button>
                <button onClick={submit} disabled={saving} className="btn-primary">
                  {saving ? <><Loader2 size={16} className="animate-spin" /> Generating…</> : <><FileText size={16} /> Generate Letter</>}
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

// ── Preview Modal ─────────────────────────────────────────────
const PreviewModal: React.FC<{ letter: RecLetter; meta: LetterMeta; onClose: () => void }> = ({ letter, meta, onClose }) => {
  const entity = letter.letter_type === 'choir' ? `${meta.church_name} Choir` : meta.church_name;

  return (
    <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[95vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b bg-gray-50 rounded-t-2xl">
          <h3 className="font-bold text-gray-900">Letter Preview — {letter.applicant_name}</h3>
          <div className="flex gap-2">
            <button onClick={() => printLetter(letter, meta)} className="btn-primary py-2 text-sm"><Printer size={15} /> Print / Download</button>
            <button onClick={onClose} className="p-2 rounded-lg text-gray-400 hover:bg-gray-100"><X size={20} /></button>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto p-8">
          {/* Letterhead */}
          <div className="flex items-start justify-between border-b-4 border-purple-700 pb-5 mb-6">
            <div className="flex items-center gap-4">
              {meta.logo_url && <img src={meta.logo_url} alt="logo" className="h-16 w-auto object-contain" />}
              <div>
                <div className="text-xl font-bold text-purple-900">{meta.church_name}</div>
                <div className="text-sm text-gray-500">{entity}</div>
              </div>
            </div>
            <div className="text-right text-xs text-gray-500 leading-relaxed">
              {meta.church_contact.split(' | ').map((c, i) => <div key={i}>{c}</div>)}
            </div>
          </div>
          {/* Letter body */}
          <div className="font-serif text-sm leading-relaxed space-y-4 text-gray-800">
            {letter.letter_content.split('\n\n').map((para, i) => {
              const t = para.trim();
              if (!t) return null;
              if (t.startsWith('____')) return <div key={i} className="border-b-2 border-gray-800 w-64 my-6" />;
              return <p key={i} className="text-justify">{t.split('\n').map((line, j) => <React.Fragment key={j}>{line}{j < t.split('\n').length - 1 && <br />}</React.Fragment>)}</p>;
            })}
          </div>
          <div className="mt-8 pt-4 border-t text-center text-xs text-gray-400">
            Generated by {meta.church_name} Management System · {new Date(letter.generated_at).toLocaleDateString()}
          </div>
        </div>
      </div>
    </div>
  );
};

// ── Main Page ─────────────────────────────────────────────────
const AdminDocuments: React.FC = () => {
  const [letters, setLetters] = useState<RecLetter[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [preview, setPreview] = useState<{ letter: RecLetter; meta: LetterMeta } | null>(null);

  const load = async () => {
    setLoading(true);
    try {
      const { letters: data } = await get<{ letters: RecLetter[] }>('/rec-letters');
      setLetters(data || []);
    } catch { } finally { setLoading(false); }
  };

  useEffect(() => { load(); }, []);

  const viewLetter = async (id: string) => {
    try {
      const res = await get<any>(`/rec-letters/${id}`);
      setPreview({ letter: res.letter, meta: { church_name: res.church_name, logo_url: res.logo_url, church_contact: res.church_contact } });
    } catch (err: any) { toast.error(err.message); }
  };

  const remove = async (id: string) => {
    if (!confirm('Delete this letter?')) return;
    try { await del(`/rec-letters/${id}`); toast.success('Deleted'); load(); }
    catch (err: any) { toast.error(err.message); }
  };

  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Recommendation Letters</h1>
          <p className="text-sm text-gray-500">Generate official church and choir recommendation letters</p>
        </div>
        <button onClick={() => setShowForm(true)} className="btn-primary"><Plus size={16} /> New Letter</button>
      </div>

      {loading ? (
        <div className="flex justify-center p-16"><Loader2 size={32} className="animate-spin text-purple-700" /></div>
      ) : letters.length === 0 ? (
        <div className="card p-16 text-center text-gray-400">
          <FileText size={48} className="mx-auto mb-4 opacity-30" />
          <p className="font-medium">No recommendation letters yet</p>
          <p className="text-sm mt-1">Click "New Letter" to generate your first one</p>
        </div>
      ) : (
        <div className="card overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b">
              <tr>{['Applicant','Letter Type','Organization','Purpose','Generated By','Date','Actions'].map((h) => (
                <th key={h} className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase">{h}</th>
              ))}</tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {letters.map((l) => (
                <tr key={l.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 font-medium text-gray-900">{l.applicant_name}</td>
                  <td className="px-4 py-3">
                    <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold capitalize ${l.letter_type === 'choir' ? 'bg-indigo-100 text-indigo-700' : 'bg-purple-100 text-purple-700'}`}>
                      {l.letter_type === 'choir' ? '🎵 Choir' : '⛪ Church'}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-gray-600">{l.org_name || '—'}</td>
                  <td className="px-4 py-3 text-gray-500 text-xs max-w-[160px] truncate">{l.purpose || '—'}</td>
                  <td className="px-4 py-3 text-gray-500 text-xs">{l.generated_by_first ? `${l.generated_by_first} ${l.generated_by_last}` : '—'}</td>
                  <td className="px-4 py-3 text-gray-500 text-xs">{new Date(l.generated_at).toLocaleDateString()}</td>
                  <td className="px-4 py-3">
                    <div className="flex gap-1">
                      <button onClick={() => viewLetter(l.id)} className="p-1.5 rounded-lg text-purple-600 hover:bg-purple-50" title="View"><Eye size={15} /></button>
                      <button onClick={() => viewLetter(l.id).then(() => {})} className="p-1.5 rounded-lg text-gray-500 hover:bg-gray-100" title="Print"><Printer size={15} /></button>
                      <button onClick={() => remove(l.id)} className="p-1.5 rounded-lg text-red-400 hover:bg-red-50" title="Delete"><Trash2 size={15} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {showForm && (
        <LetterForm
          onClose={() => setShowForm(false)}
          onSuccess={(letter, meta) => {
            setShowForm(false);
            load();
            setPreview({ letter, meta });
          }}
        />
      )}

      {preview && <PreviewModal letter={preview.letter} meta={preview.meta} onClose={() => setPreview(null)} />}
    </div>
  );
};

export default AdminDocuments;
